title:  Finalwind
email: zhangjia__@outlook.com
description: >
  A student in senior highschool

gems: [jekyll-paginate]
paginate: 10
paginate_path: "/page:num"
url: "https://finalwind1.github.io"
enforce_ssl: 
twitter_username: 
github_username:  zhangjia00
markdown: kramdown
