# Site settings
title: Finalwind	
name: Zhang jia # your name
email: zhangjia__@outlook.com # your email address
description: >
    Finalwind Blog # this means to ignore newlines until "baseurl:"
baseurl: "/Nice_Blog" # the subpath of your site, e.g. /blog
url: "https://finalwind1.github.io" # the base hostname & protocol for your site
twitter_username:   # your Twitter username
github_username: zhangjia00 # your Github username
disqus_username:  # your disqus username

google-analytics:  # add it if you have one

skillstree: off # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
